spring.application.name=api-gateway
server.port=9000
#Automatic Routes
#spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
#spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
token.secret=QkzXW7hFhXz4qkYwX3zv6uFZkYwYz9vXh6p3t2r5u8s9d0a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6A7B8C9D0E1F2G3H4I5J6K7L8M9N0O1P2Q3R4S5T6U7V8W9X0Y1Z2

# Allow Angular dev server origin
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:4200

# Allow HTTP methods
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS

# Allow all headers
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-headers=*

# Allow credentials
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allow-credentials=true

# Important: enable CORS for OPTIONS preflight requests
spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true



